<?php

use App\Enums\PermissionKey;
use App\Enums\RoleName;

return [
    'permissions' => PermissionKey::values(),

    'default_account_password' => env('RBAC_DEFAULT_ACCOUNT_PASSWORD', 'password'),

    'default_accounts' => [
        [
            'name' => 'FieldOps User',
            'email' => 'user@example.com',
            'role' => RoleName::User->value,
        ],
        [
            'name' => 'FieldOps Admin',
            'email' => 'admin@example.com',
            'role' => RoleName::Admin->value,
        ],
        [
            'name' => 'FieldOps Super Admin',
            'email' => 'superadmin@example.com',
            'role' => RoleName::SuperAdmin->value,
        ],
    ],

    'roles' => [
        RoleName::User->value => [
            'display_name' => 'User',
            'description' => 'Basic access to the FieldOps dashboard.',
            'is_system' => true,
            'permissions' => [
                PermissionKey::DashboardView->value,
                PermissionKey::MediaAssetsView->value,
                PermissionKey::MediaAssetsCreate->value,
                PermissionKey::MediaAssetsUpdate->value,
                PermissionKey::MediaAssetsDelete->value,
            ],
        ],
        RoleName::Admin->value => [
            'display_name' => 'Admin',
            'description' => 'Manage users, roles, invitations, and access history.',
            'is_system' => true,
            'permissions' => [
                PermissionKey::DashboardView->value,
                PermissionKey::UsersView->value,
                PermissionKey::UsersCreate->value,
                PermissionKey::UsersInvite->value,
                PermissionKey::UsersUpdate->value,
                PermissionKey::UsersDelete->value,
                PermissionKey::UsersSuspend->value,
                PermissionKey::UsersReviewRegistrations->value,
                PermissionKey::UsersViewDeleted->value,
                PermissionKey::UsersUpdateDeleted->value,
                PermissionKey::RolesView->value,
                PermissionKey::RolesCreate->value,
                PermissionKey::RolesUpdate->value,
                PermissionKey::RolesDelete->value,
                PermissionKey::RolesAssign->value,
                PermissionKey::RolesViewDeleted->value,
                PermissionKey::RolesUpdateDeleted->value,
                PermissionKey::AuditView->value,
                PermissionKey::IpBlocksView->value,
                PermissionKey::IpBlocksCreate->value,
                PermissionKey::IpBlocksUpdate->value,
                PermissionKey::IpBlocksDelete->value,
                PermissionKey::IpBlocksViewDeleted->value,
                PermissionKey::IpBlocksUpdateDeleted->value,
                PermissionKey::VisitLogsView->value,
                PermissionKey::SettingsView->value,
                PermissionKey::SettingsUpdate->value,
                PermissionKey::CountriesView->value,
                PermissionKey::CountriesCreate->value,
                PermissionKey::CountriesUpdate->value,
                PermissionKey::CountriesDelete->value,
                PermissionKey::CountriesViewDeleted->value,
                PermissionKey::CountriesUpdateDeleted->value,
                PermissionKey::TimezonesView->value,
                PermissionKey::TimezonesCreate->value,
                PermissionKey::TimezonesUpdate->value,
                PermissionKey::TimezonesDelete->value,
                PermissionKey::TimezonesViewDeleted->value,
                PermissionKey::TimezonesUpdateDeleted->value,
                PermissionKey::OrganizationLocationsView->value,
                PermissionKey::OrganizationLocationsCreate->value,
                PermissionKey::OrganizationLocationsUpdate->value,
                PermissionKey::OrganizationLocationsDelete->value,
                PermissionKey::OrganizationLocationsViewDeleted->value,
                PermissionKey::OrganizationLocationsUpdateDeleted->value,
                PermissionKey::MediaAssetsView->value,
                PermissionKey::MediaAssetsCreate->value,
                PermissionKey::MediaAssetsUpdate->value,
                PermissionKey::MediaAssetsDelete->value,
                PermissionKey::MediaAssetsViewDeleted->value,
                PermissionKey::MediaAssetsUpdateDeleted->value,
            ],
        ],
        RoleName::SuperAdmin->value => [
            'display_name' => 'Super Admin',
            'description' => 'Full enterprise access and platform administration controls.',
            'is_system' => true,
            'permissions' => PermissionKey::values(),
        ],
    ],
];
